# YAML EXPLANATION FILE #

Name: NoNemous87
Languages: Python,Shell-script,Javascript,Php,Css,Powershell,Batch,C++,Java
Python-Version: Python 3 
Author: NoNe
Copyright: (C) 2026 nonemous87@gmail.com>
Copyright-Years: 2021,2022,2023,2024,2025,2026
Download: git clone https://github.com/NoNemous87/NoNe87
Platforms: Linux/MacOS/Termux/Windows
Version: T.G.D-1.0.4
License: Mozilla Public License Version 2.0
